# fail2ban для игрового лобби на :8090
[DEFAULT]
ignoreip = 127.0.0.1/8 ::1

[nginx-limit-req]
enabled = true
filter = nginx-limit-req
port = 8090
protocol = tcp
logpath = /var/log/nginx/minecraft-panel.error.log
backend = auto
maxretry = 15
findtime = 60
bantime = 7200
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 86400

[nginx-botsearch]
enabled = true
filter = nginx-botsearch
port = 8090
protocol = tcp
logpath = /var/log/nginx/minecraft-panel.access.log
backend = auto
maxretry = 2
findtime = 600
bantime = 86400

[nginx-panel-444]
enabled = true
filter = nginx-panel-444
port = 8090
protocol = tcp
logpath = /var/log/nginx/minecraft-panel.access.log
backend = auto
maxretry = 8
findtime = 300
bantime = 43200
